var wordData = {
    words: [
        {
            list: [
              {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 1 ,word: "wear",mean: "~를 입다, 착용하다(상태)"}  ,
              {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 2 ,word: "hold",mean: "~을 잡다, 들다"} , 
              {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 3 ,word: "pour",mean: "~를 붓다, 따르다"}  ,
              {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 4 ,word: "leaning against/over/on",mean: "~에 기대다, 몸을 기울이다"}  ,
              {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 5 ,word: "kneel",mean: "무릎을 꿇다"}  ,
              {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 6 ,word: "push",mean: "~을 밀다"}  ,
              {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 7 ,word: "wait",mean: "기다리다"}  ,
              {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 8 ,word: "examine",mean: "~을 자세히 들여다보다"}  ,
              {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 9 ,word: "wipe",mean: "~(의 표면)을 닦다"}  ,
              {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 10 ,word: "face",mean: "~을 향하다"}  ,
              {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 11 ,word: "bend",mean: "몸을 구부리다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 12 ,word: "gather",mean: "모이다, ~을 모으다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 13 ,word: "be seated",mean: "착석하다, 앉아 있다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 14 ,word: "purchase",mean: "~을 구매하다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 15 ,word: "place",mean: "~을(···에)놓다, ~을(···에)위치시키다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 16 ,word: "load",mean: "~을 싣다, ~에 싣다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 17 ,word: "distribute",mean: "~을 나눠주다, 배부하다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 18 ,word: "look in(to)",mean: "~을 들여다보다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 19 ,word: "trim",mean: "~(나뭇가지 등)을 다듬다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 20 ,word: "climb",mean: "~을 오르다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 21 ,word: "board",mean: "~을 타다, ~에 오르다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 22 ,word: "sweep",mean: "~을(긴 빗자루로) 쓸다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 23 ,word: "prepare",mean: "~을 준비하다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 24 ,word: "step",mean: "발을 내딛다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 25 ,word: "enter",mean: "~에 들어가다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 26 ,word: "stroll",mean: "천천히 거닐다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 27 ,word: "adjust",mean: "(장치 등을)조정하다, 조절하다, 맞추다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 28 ,word: "arrange",mean: "~을 정렬하다, 정리하다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 29 ,word: "lift",mean: "~을 들어올리다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 30 ,word: "rest",mean: "휴식을 취하다(= relax)"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 31 ,word: "cross",mean: "~을 건너다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 32 ,word: "tie",mean: "~을 묶다, 메다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 33 ,word: "reach",mean: "손을 뻗다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 34 ,word: "point at/to",mean: "~을 가리키다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 35 ,word: "dine",mean: "식사하다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 36 ,word: "remove",mean: "~을 꺼내다, 빼다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 37 ,word: "stand",mean: "서 있다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 38 ,word: "pose",mean: "포즈를 취하다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 39 ,word: "work",mean: "작업하다"}  ,
            //   {week:1 , day: 1 ,title:"사람 사진 빈출 어휘" ,id: 40 ,word: "pack",mean: "짐을 싸다, 가방을 꾸리다"}  ,
            ],
        }, 
        {
            list: [
              {word: "dog",mean: "개"}  ,
              {word: "cat",mean: "고양이"},  
              {word: "bird",mean: "새"}  
            ],
        }, 
    ],
};